// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Admin struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	Name         string `json:"name"`
	PasswordHash string `json:"password_hash"`
}

type Invitation struct {
	ID   string `json:"id"`
	Data string `json:"data"`
}

type Session struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	CsrfToken string    `json:"csrf_token"`
	ExpiresAt time.Time `json:"expires_at"`
}

type Setting struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}
