// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package db

import (
	"context"
	"time"
)

const adminExists = `-- name: AdminExists :one
SELECT EXISTS(SELECT 1 FROM admins WHERE email = ?)
`

func (q *Queries) AdminExists(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, adminExists, email)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countInvitations = `-- name: CountInvitations :one
SELECT COUNT(*) FROM invitations
`

func (q *Queries) CountInvitations(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countInvitations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdmin = `-- name: CreateAdmin :exec
INSERT INTO admins (id, email, password_hash)
VALUES (?, ?, ?)
`

type CreateAdminParams struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) error {
	_, err := q.db.ExecContext(ctx, createAdmin, arg.ID, arg.Email, arg.PasswordHash)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, email, csrf_token, expires_at)
VALUES (?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	CsrfToken string    `json:"csrf_token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.Email,
		arg.CsrfToken,
		arg.ExpiresAt,
	)
	return err
}

const deleteAdmin = `-- name: DeleteAdmin :exec
DELETE FROM admins
WHERE id = ?
`

func (q *Queries) DeleteAdmin(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAdmin, id)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteInvitation = `-- name: DeleteInvitation :exec
DELETE FROM invitations
WHERE id = ?
`

func (q *Queries) DeleteInvitation(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteInvitation, id)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getAdmin = `-- name: GetAdmin :one
SELECT id, email, password_hash FROM admins
WHERE email = ? LIMIT 1
`

func (q *Queries) GetAdmin(ctx context.Context, email string) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdmin, email)
	var i Admin
	err := row.Scan(&i.ID, &i.Email, &i.PasswordHash)
	return i, err
}

const getAllParticipants = `-- name: GetAllParticipants :many
SELECT DISTINCT json_extract(pi.value, '$.participant_email') as email
FROM invitations, json_each(json_extract(invitations.data, '$.personal_invites')) as pi
`

func (q *Queries) GetAllParticipants(ctx context.Context) ([]interface{}, error) {
	rows, err := q.db.QueryContext(ctx, getAllParticipants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var email interface{}
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInvitation = `-- name: GetInvitation :one
SELECT id, data FROM invitations
WHERE id = ? LIMIT 1
`

func (q *Queries) GetInvitation(ctx context.Context, id string) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, getInvitation, id)
	var i Invitation
	err := row.Scan(&i.ID, &i.Data)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, email, csrf_token, expires_at FROM sessions
WHERE id = ? LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CsrfToken,
		&i.ExpiresAt,
	)
	return i, err
}

const listAdmins = `-- name: ListAdmins :many
SELECT id, email, password_hash FROM admins
`

func (q *Queries) ListAdmins(ctx context.Context) ([]Admin, error) {
	rows, err := q.db.QueryContext(ctx, listAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Admin
	for rows.Next() {
		var i Admin
		if err := rows.Scan(&i.ID, &i.Email, &i.PasswordHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvitations = `-- name: ListInvitations :many
SELECT id, data FROM invitations
ORDER BY rowid DESC
LIMIT ? OFFSET ?
`

type ListInvitationsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListInvitations(ctx context.Context, arg ListInvitationsParams) ([]Invitation, error) {
	rows, err := q.db.QueryContext(ctx, listInvitations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invitation
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(&i.ID, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveInvitation = `-- name: SaveInvitation :exec
INSERT INTO invitations (id, data) VALUES (?, ?)
ON CONFLICT(id) DO UPDATE SET data = excluded.data
`

type SaveInvitationParams struct {
	ID   string `json:"id"`
	Data string `json:"data"`
}

func (q *Queries) SaveInvitation(ctx context.Context, arg SaveInvitationParams) error {
	_, err := q.db.ExecContext(ctx, saveInvitation, arg.ID, arg.Data)
	return err
}
