// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package db

import (
	"context"
)

const adminExists = `-- name: AdminExists :one
SELECT EXISTS(SELECT 1 FROM admins WHERE username = ?)
`

func (q *Queries) AdminExists(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRowContext(ctx, adminExists, username)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createAdmin = `-- name: CreateAdmin :exec
INSERT INTO admins (id, username, password_hash)
VALUES (?, ?, ?)
`

type CreateAdminParams struct {
	ID           string `json:"id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) error {
	_, err := q.db.ExecContext(ctx, createAdmin, arg.ID, arg.Username, arg.PasswordHash)
	return err
}

const getAdmin = `-- name: GetAdmin :one
SELECT id, username, password_hash FROM admins
WHERE username = ? LIMIT 1
`

func (q *Queries) GetAdmin(ctx context.Context, username string) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdmin, username)
	var i Admin
	err := row.Scan(&i.ID, &i.Username, &i.PasswordHash)
	return i, err
}

const getAllParticipants = `-- name: GetAllParticipants :many
SELECT DISTINCT json_extract(pi.value, '$.participant_email') as email
FROM invitations, json_each(json_extract(invitations.data, '$.personal_invites')) as pi
`

func (q *Queries) GetAllParticipants(ctx context.Context) ([]interface{}, error) {
	rows, err := q.db.QueryContext(ctx, getAllParticipants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var email interface{}
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInvitation = `-- name: GetInvitation :one
SELECT id, data FROM invitations
WHERE id = ? LIMIT 1
`

func (q *Queries) GetInvitation(ctx context.Context, id string) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, getInvitation, id)
	var i Invitation
	err := row.Scan(&i.ID, &i.Data)
	return i, err
}

const listInvitations = `-- name: ListInvitations :many
SELECT id, data FROM invitations
`

func (q *Queries) ListInvitations(ctx context.Context) ([]Invitation, error) {
	rows, err := q.db.QueryContext(ctx, listInvitations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invitation
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(&i.ID, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveInvitation = `-- name: SaveInvitation :exec
INSERT INTO invitations (id, data) VALUES (?, ?)
ON CONFLICT(id) DO UPDATE SET data = excluded.data
`

type SaveInvitationParams struct {
	ID   string `json:"id"`
	Data string `json:"data"`
}

func (q *Queries) SaveInvitation(ctx context.Context, arg SaveInvitationParams) error {
	_, err := q.db.ExecContext(ctx, saveInvitation, arg.ID, arg.Data)
	return err
}
